name: Power Broker Node Step
rundeckPluginVersion: 1.0
author: Alex Honor
date: 11/05/2015
version: 1.0
providers:
    - name: pbrun-step
      service: WorkflowNodeStep
      title: pbrun-step
      description: Executes the command via ssh to the remote node and executs command using pbrun.
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: exec.sh
      script-args: ${node.username} ${node.hostname} ${exec.command}
      config:
        - name: service_account
          title: service account
          type: String
          required: true
          description: service account to use for remote ssh connection
        - name: pbrun_cmd
          title: pbrun command
          type: String
          required: true
          description: executable to use for pbrun
        - name: ssh_key_storage_path
          title: SSH key Storage Path
          type: String
          required: false
          description: "Storage path for ssh-key file. Can contain property references to node attributes. A node attribute named ssh-key-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            instance-scope-node-attribute: "ssh-key-storage-path"
